### ISSUE TITLE
Install Chrome on Ubuntu Server 14.04

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/whisper#93]
We changed our development environment from *Ubuntu Desktop 11.04* within *VirtualBox 4.1.10* to an existing *Windows 7* machine and [dual booting](https://github.com/jeff1evesque/audio-analyzer/issues/354) it with *Ubuntu Server 14.04*.

This should allow us to install *Google Chrome*, and avoid our previous [difficulties](https://github.com/jeff1evesque/whisper/issues/51#issuecomment-49300743).

**Comment by tcelestino** [comment]
Try this: sudo apt-get install libindicator7

**Comment by jeff1evesque** [comment]
@tcelestino, thank you!  I've made implied suggestion to the [documentation](https://github.com/jeff1evesque/whisper/blob/48053196d223d79050885caaf45c5bf08741f59a/README.md).  I will try to be more [explicit](https://github.com/jeff1evesque/whisper/issues/180).

**Comment by tcelestino** [comment]
:+1:
